### PR TITLE
Update primary officers' policy

### PR DESCRIPTION
**Pull request by wadeanthony0100**
This document is pretty out of date, so here are my proposed changes. Feel free to propose / make edits as you feel necessary.

This doc gets published to the site, so it would be nice to get at least a rough draft into production to replace to information that's currently there as soon as possible. We can get individual officers' input after the fall semester starts.

### CODE REVIEW

**Comment by wadeanthony0100** [comment]
@robmcl4

**Comment by wadeanthony0100** [comment]
@DanTheManGude

**Comment by kristenmills** [comment]
Primary officer policy doesn't need that...that's only for actual constitution amendments.

**Comment by 7imbrook** [comment]
@kristenmills ik, now make ci pass, cause I can't get to the job.

**Comment by kristenmills** [comment]
@7imbrook I don't have permission.

**Pull request merged**
